/************************************
*    Mustafa Efekan PEKEL 150140050
*       email= pekelm@itu.edu.tr
*     BIL105 Spring Term CRN: 21831
*              Homework-2
************************************/

#include <stdio.h>
int range1=0,range2=0,range3=0,range4=0,range5=0;                   //ranges
long long int mod;

void mid_rng(long *number) {                                        //prng-mid
    long long int square;
    square = (long long int) *number * (long long int)*number;
    if(square>=1000000000){                                         //if the number has 10 digits
        long long int temp = square % 100000000;
        *number = temp / 1000;
    }
    else if(square>=100000000) {                                    //if the number has 9 digits
        long long int temp = square % 10000000;
        *number = temp / 100;
    }
    else if(square>=10000000) {                                     //if the number has 8 digits
        long long int temp = square % 10000000;
        *number = temp / 100;
    }
    else if(square>=1000000) {                                      //if the number has 7 digits
        long long int temp = square % 1000000;
        *number = temp/10;
    }
     else if(square>=100000) {                                      //if the number has 6 digits
        long long int temp = square;
        *number = temp/10;
    }
    else{                                                           //if the number has 5 digits
        long long int temp = square;
        *number = temp;
    }
    mod = *number % 500 + 1 ;                                       //calculating modula to determine the number's range

}

void lsd_rng(long *number) {                                        //prng-lsd
    long long int product;
    long long int temp;
    product = *number * 73;
    temp = product%1000000;                                         //take rightmost 5 digits
    *number = temp;
    mod = *number % 500 + 1 ;                                       //calculating modula to determine the number's range
}




void take_samples(int selection, int num_samples, long int seed){
    int i;
    for(i=0;i<num_samples;i++) {                                    //generates numbers "num_samples" times
        if(selection == 1) mid_rng(&seed);                          //according to user selection decides the prng algorithm
        else if(selection == 2) lsd_rng(&seed);
        if(mod>400){                                                //maps every generated number according to range limits
            range5++;
        }
        else if(mod>300){
            range4++;
        }
        else if(mod>200){
            range3++;
        }
        else if(mod>100){
            range2++;
        }
        else{
            range1++;
        }
    }

}

void print_histogram(int num_samples) {
    int i;
    int range1p = range1 * 100 / num_samples;                       //calculates the percentage
    int range2p = range2 * 100 / num_samples;
    int range3p = range3 * 100 / num_samples;
    int range4p = range4 * 100 / num_samples;
    int range5p = range5 * 100 / num_samples;

    printf("  1..100: ");                                           //printing histogram according to sample output in the homework file
    for(i=0;i<range1p;i++){
        printf("*");
    }
    printf(" (%d%%)\n",range1p);

    printf("101..200: ");
    for(i=0;i<range2p;i++){
        printf("*");
    }
    printf(" (%d%%)\n",range2p);

    printf("201..300: ");
    for(i=0;i<range3p;i++){
        printf("*");
    }
    printf(" (%d%%)\n",range3p);

    printf("301..400: ");
    for(i=0;i<range4p;i++){
        printf("*");
    }
    printf(" (%d%%)\n",range4p);

    printf("401..500: ");
    for(i=0;i<range5p;i++){
        printf("*");
    }
    printf(" (%d%%)\n",range5p);
}




int main() {

    printf("Which PRNG Algorithm?\n");
    printf(" 1. MID-PRNG\n");
    printf(" 2. LSD-PRNG\n");
    int selection=0;
    while(selection != 1 && selection !=2) {
        scanf("%d",&selection);                                     //asks for a suitable selection input until user gives a valid one
    }
    long int seed;
    int num_samples,i;
    switch(selection){
    case 1:
        printf("Enter the seed\n");
        scanf("%ld",&seed);                                         //asks the seed for MID-PRNG method
        printf("Enter Number of Samples\n");
        scanf("%d",&num_samples);
        take_samples(selection, num_samples, seed);
        printf("%d random numbers were generated by using MID-PRNG:\n",num_samples);
        print_histogram(num_samples);
        break;
    case 2:
        seed = 0;
        while(seed % 2 ==0 || seed % 10 == 5 ){                     //asks for a suitable seed until user gives a valid one
            printf("Enter the seed\n");
            scanf("%ld",&seed);
        }
        printf("Enter Number of Samples\n");
        scanf("%d",&num_samples);
        take_samples(selection, num_samples, seed);
        printf("%d random numbers were generated by using LSD-PRNG:\n",num_samples);
        print_histogram(num_samples);
        break;
    }



    return 0;

}
